version: '3.7'

services:
  ubuntu:
    image: ubuntu:18.04

  php:
    restart: "no"
    build:
      context: ./docker/services/php
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./docker/services/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./${WWW_PATH}:${CODE_PATH}

  nginx:
    image: nginx:latest
    restart: "no"
    volumes:
      - ./${WWW_PATH}:${CODE_PATH}
      - ./docker/services/nginx/conf.d:/etc/nginx/conf.d
      - ${NGINX_LOG_PATH}:/var/log/nginx
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"

  mysql:
    restart: "no"
    build:
      context: ./docker/services/mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
        - DB_PORT=${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ${MYSQL_DATABASE_PATH}:/var/lib/mysql
      - ${MYSQL_LOG_PATH}:/var/log/mysql/
      - ./docker/services/mysql/config-overrides.cnf:/etc/mysql/conf.d/my.cnf

  redis:
    build: ./docker/services/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./docker/services/redis:/etc/redis/redis.conf
    sysctls:
      net.core.somaxconn: '511'
